language: go
go:
   - "1.10"
install:
   - go get -u github.com/golang/dep/cmd/dep/...
   - go get -u github.com/alecthomas/gometalinter/...
   - gometalinter --install
script: make ci
services:
   - docker
deploy:
   - provider: script
     skip_cleanup: true
     script: bash ci_release.sh
     on:
        tags: true
        condition: $TRAVIS_OS_NAME = linux

