[[constraint]]
  name = "github.com/CyCoreSystems/ari"
  version = "5.0.0-pre3"

[[constraint]]
  name = "github.com/inconshreveable/log15"
  version = "2.13.0"

[[constraint]]
  name = "github.com/nats-io/nats"
  version = "1.5.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.2"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"
