[[constraint]]
  name = "github.com/CyCoreSystems/ari"
  version = "4.1.2"

[[constraint]]
  name = "github.com/inconshreveable/log15"
  version = "2.11.0"

[[constraint]]
  name = "github.com/nats-io/nats"
  version = "1.3.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.1.0"

[[constraint]]
  name = "github.com/spf13/cobra"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"
